import { createSlice } from '@reduxjs/toolkit';

const products = createSlice({
  name: 'products',
  initialState: [
    {
      id: 1,
      img: 'https://images.pexels.com/photos/2690323/pexels-photo-2690323.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 20,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 2,
      img: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 35,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 3,
      img: 'https://images.pexels.com/photos/1375736/pexels-photo-1375736.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 31,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 4,
      img: 'https://images.pexels.com/photos/1342609/pexels-photo-1342609.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 28,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 5,
      img: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 25,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 6,
      img: 'https://images.pexels.com/photos/1040384/pexels-photo-1040384.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 23,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 7,
      img: 'https://images.pexels.com/photos/1381553/pexels-photo-1381553.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 22,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
    {
      id: 8,
      img: 'https://images.pexels.com/photos/3387577/pexels-photo-3387577.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'descent item',
      desc: ' dolor sit amet consectetur adipisicing elit. Cum vero, natus minus dolore aut rem esse ea ducimus explicabo totam architecto reiciendis debitis eveniet dicta quaerat, blanditiis optio voluptas quia.',
      price: 30,
      color: { red: 'red', blue: 'blue', green: 'green' },
      size: { small: 'sm', madium: 'md', large: 'lg', extralarge: 'xlg' },
    },
  ],
  reducers: {},
});
export default products.reducer;
